src/Entity/Programme.php
<?php

namespace App\Entity;

use App\Repository\ProgrammeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProgrammeRepository::class)]
class Programme
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nbjours = null;

    #[ORM\ManyToOne(inversedBy: 'programmes')]
    private ?Session $session = null;

    #[ORM\ManyToOne(inversedBy: 'programmes')]
    private ?ModuleSession $module_session = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbjours(): ?int
    {
        return $this->nbjours;
    }

    public function setNbjours(int $nbjours): static
    {
        $this->nbjours = $nbjours;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): static
    {
        $this->session = $session;

        return $this;
    }

    public function getModuleSession(): ?ModuleSession
    {
        return $this->module_session;
    }

    public function setModuleSession(?ModuleSession $module_session): static
    {
        $this->module_session = $module_session;

        return $this;
    }

    public function __toString()
    {
        return $this->session." ".$this->module_session." "." ".$this->nbjours. " jours";
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateSessionDebut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateSessionFin = null;

    #[ORM\Column]
    private ?int $places = null;

    #[ORM\ManyToMany(targetEntity: Stagiaire::class, mappedBy: 'sessions')]
    private Collection $stagiaires;

    #[ORM\ManyToOne(inversedBy: 'session')]
    private ?Formation $formation = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Formateur $formateur = null;

    #[ORM\OneToMany(mappedBy: 'session', targetEntity: Programme::class, orphanRemoval:true)]
    private Collection $programmes;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $coordonnees = null;

    public function __construct()
    {
        $this->stagiaires = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateSessionDebut(): ?\DateTimeInterface
    {
        return $this->dateSessionDebut;
    }

    public function getDateSessionDebutFormat(): ?string
    {
        return $this->dateSessionDebut->format("Y-m-d");
    }

    public function setDateSessionDebut(\DateTimeInterface $dateSessionDebut): static
    {
        $this->dateSessionDebut = $dateSessionDebut;

        return $this;
    }

    public function getDateSessionFin(): ?\DateTimeInterface
    {
        return $this->dateSessionFin;
    }

    public function getDateSessionFinFormat(): ?string
    {
        return $this->dateSessionFin->format("Y-m-d");
    }


    public function setDateSessionFin(\DateTimeInterface $dateSessionFin): static
    {
        $this->dateSessionFin = $dateSessionFin;

        return $this;
    }

    public function getPlaces(): ?int
    {
        return $this->places;
    }

    public function getInscrits(): ?int
    {
        return count($this->stagiaires);
    }

    public function getPlacesRestantes() : ?int
    {
        return $this->places - $this->getInscrits();
    }

    // public function setPlacesRestantes(int $places, int $nbInscrits): static
    // {
    //     $this->places = $places - $nbInscrits;

    //     return $this;
    // }

    public function setPlaces(int $places): static
    {
        $this->places = $places;

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): static
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->add($stagiaire);
            $stagiaire->addSession($this);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): static
    {
        if ($this->stagiaires->removeElement($stagiaire)) {
            $stagiaire->removeSession($this);
        }

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): static
    {
        $this->formateur = $formateur;

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->titre;
    }

    public function getCoordonnees(): ?string
    {
        return $this->coordonnees;
    }

    public function setCoordonnees(?string $coordonnees): static
    {
        $this->coordonnees = $coordonnees;

        return $this;
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Formateur;
use App\Entity\Formation;
use App\Entity\Stagiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre' , TextType::class, [

            ])
            ->add('dateSessionDebut', DateType::class, [
                'widget' =>'single_text',

            ])
            ->add('dateSessionFin', DateType::class, [
                'widget' =>'single_text',
                'constraints' => [
                    new NotBlank(), 
                    new GreaterThan([
                        'message' => 'La date de fin doit être supérieure à celle de début',
                        'propertyPath' => 'parent.all[dateSessionDebut].data' //Thanks StackOverflow 
                    ])
                ]
            ])
            ->add('places', NumberType::class, [

            ])
            ->add('formation', EntityType::class, [
                'class' => Formation::class,

            ])
            ->add('formateur', EntityType::class , [
                'class' => Formateur::class,
            ])

            ->add('coordonnees', TextType::class, ['attr' => ['class' => 'coordinates']])

            ->add('valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
            'csrf_protection' => true,
            'csrf_field_name' => '_token', // The name of the CSRF field in your form
            'csrf_token_id' => 'your_csrf_token_id',
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Programme;
use App\Entity\Stagiaire;
use App\Form\SessionType;
use App\Entity\ModuleSession;
use App\Repository\SessionRepository;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SessionController extends AbstractController
{
    
    #[Route('profile/sessions', name: 'globalSession')]
    public function index(SessionRepository $sessionRepository): Response
    {

        $sessions = $sessionRepository->findBy([], ["titre" => "ASC"]);
        $sessionsAVenir = $sessionRepository->findSessionsAVenir();
        $sessionsEnCours = $sessionRepository->findSessionsEnCours();
        $sessionsFinies = $sessionRepository->findSessionsFinies();
        $currentDate = new \DateTime;
        $currentDate = $currentDate->format("Y-m-D");
        $marqueurs = [];
        foreach ($sessions as $session)
        {
            if ($session->getCoordonnees()) 
            {
                $marqueurs[] = [
                    'id' => $session->getId(),
                    'latlng' => $session->getCoordonnees()
                ];
            }
        }

        $marqueurs = json_encode([$marqueurs]);
        // foreach ($sessions as $session) Trying to do counting via controller  i get good arrays but i dunno how i can use it to say give index 0 to session id 1 etc.
        // {
        //     $placesRestantes = 0;

        //     foreach ($session->getStagiaires() as $stagiaire)
        //     {
        //         $placesRestantes = $placesRestantes + 1;
        //     }
        //     $arrayCount[$session->getId()] = $session->getPlaces() - $placesRestantes;
        // }


        return $this->render('session/index.html.twig', [
            'sessions' => $sessions,
            'sessionsAVenir' => $sessionsAVenir,
            'sessionsEnCours' => $sessionsEnCours,
            'sessionsFinies' => $sessionsFinies,
            'currentDate' => $currentDate,
            'marqueurs' => $marqueurs,
            // 'arrayCount' => $arrayCount,
        ]);
    }

    #[Route('admin/session/{id}/delete', name: 'deleteSession')]
    public function sessionDelete(Session $session, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($session);
        $entityManager->flush();
        return $this->redirectToRoute('globalSession');
    }

    #[Route('profile/session_session/remove/stagiaire/{id}/{session}', name: 'removeStagiaire', priority: 1000 )] //Higher prio 
    public function removeStagiaire(Stagiaire $stagiaire, Session $session, EntityManagerInterface $entityManager): Response
    {
        $idToRedirect = [];
        $idToRedirect['id'] = $session->getId();
        var_dump($idToRedirect);
        $session->removeStagiaire($stagiaire);
        $entityManager->flush();
        return $this->redirectToRoute('detailSession', $idToRedirect);
    }

    #[Route('admin/session/new', name: 'newSession')]
    #[Route('admin/session/{id}/edit', name: 'editSession')]
    public function new(Session $session = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        // creates a task object and initializes some data for this example
        if ($session === null)
        {
            $session = new Session();            
        }
        $form = $this->createForm(SessionType::class , $session);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) 
            {
                $session = $form->getData();
                $entityManager->persist($session); //traditional prepare / execute in SQL
                $entityManager->flush();

                $this->addFlash // need to be logged as user to see the flash messages build-in Symfony
                (
                    'notice',
                    'Your changes were saved!'
                );

                return $this->redirectToRoute('globalSession'); //redirect to list stagiaires if everything is ok
            }
        
        return $this->render("session/new.html.twig", ['formNewSession' => $form]);
    }



    #[Route('profile/session/{id}', name: 'detailSession')]
    public function sessionDetail(Session $session, SessionRepository $sessionRepo, StagiaireRepository $stagiaireRepository): Response
    {
        $totalNbJours = 0;
        foreach ($session->getProgrammes() as $prog)
        {
            $totalNbJours = $totalNbJours + $prog->getNbJours();
        }
        $allStagiaires = $stagiaireRepository->findBy([], ["nom" => "ASC"]);
        $stagiairesNonInscrits = $sessionRepo->findNonInscrits($session->getId());
        $modulesnonconcernes = $sessionRepo->findModulesNonConcernes($session->getId());
        return $this->render('session/detail.html.twig', [
            'session' => $session,
            'stagiairesNonInscrits' => $stagiairesNonInscrits,
            'modulesnonconcernes' => $modulesnonconcernes,
            'totalNbJours' => $totalNbJours,
            'allStagiaires' => $allStagiaires
        ]);
    }

    #[Route('admin/session/addStagiaire/{id}/{session}', name: 'addStagiaire')]
    public function addStagiaire(Stagiaire $stagiaire, Session $session, EntityManagerInterface $entityManager): Response
    {
        $idToRedirect = [];
        $idToRedirect['id'] = $session->getId();
        if ($session->getPlacesRestantes() == 0)
        {
            $this->redirectToRoute('detailSession', $idToRedirect);
        }        
        $session->addStagiaire($stagiaire);
        $entityManager->flush();
        return $this->redirectToRoute('detailSession', $idToRedirect);
    }

    #[Route('admin/session/{id}/addModule/{session}', name: 'addModule')]
    public function addProgramme(Request $request, ModuleSession $modulesession, Session $session, EntityManagerInterface $entityManager): Response
    {
        //adding a new module means creatig a new programme
        $programme = new Programme;
        $idToRedirect = [];
        $idToRedirect['id'] = $session->getId();
        $nbjours = $request->request->get("number"); // get form field named "number"
        //setting new programme properties
        // $programme->setNbJours(intval($_POST["number"]));  That's what we would do in classic php 
        $programme->setNbjours($nbjours);
        $programme->setModuleSession($modulesession);
        $programme->setSession($session);
        $session->addProgramme($programme);
        $entityManager->persist($programme);
        $entityManager->flush();
        return $this->redirectToRoute('detailSession', $idToRedirect);
    }

    #[Route('admin/session/{id}/removeProgramme/{programme}', name: 'removeProgramme')]
    public function removeProgramme(Programme $programme, Session $session, EntityManagerInterface $entityManager): Response
    {
        $idToRedirect = [];
        $idToRedirect['id'] = $session->getId();
        $session->removeProgramme($programme);
        $entityManager->persist($programme);
        $entityManager->flush();
        return $this->redirectToRoute('detailSession', $idToRedirect);
    }
}

templates/session/detail.html.twig
{% extends 'base.html.twig' %}

{% block meta %}
<meta name="description" content="Détail de la session">
{% endblock %}

{% block title %}Hello SessionController!{% endblock %}


{% block body %}
<div class="encard">
    <h1>Caractérisque de la seesion : {{ session.titre }} </h1>
    {% if is_granted("ROLE_ADMIN") %}
        <p><a class="looksLikeAButton" href=" {{ path("editSession", {"id" : session.id }) }}">Modifier les détails de la session</a></p>        
    {% endif %}
    <p class="zero center"><b>Nom du référant formateur</b> : {{ session.formateur.nom }} {{ session.formateur.prenom }} </p>
    <p class="zero center"><b>Contenu de la formation</b> : {{ session.formation.intitule }} </p>
    <p class="zero center"><b>Modules concernées</b> : 
        {% if session.programmes is empty %}
            aucun module n'a été trouvé.
        {% else %}
            {% for prog in session.programmes %} 
                {% if prog.moduleSession is not null %}
                    {{ prog.moduleSession.nom }} 
                {% endif %}
            {% endfor %}
        {% endif %}
    </p>
    <p class="zero center"><b>La session démarre le</b> : <span class="red" >{{ session.dateSessionDebutFormat }}</span></p>
    <p class="zero center"><b>La session se termine le</b> : <span class="red" >{{ session.dateSessionFinFormat }}</span></p>

    {% set  currentDate = "now"|date("Y-m-d") %}
    {% if currentDate > session.dateSessionFinFormat %} {# below cases to display when a session is open or closed #}
        <p class="zero center">Cette session est <b>terminée.</b></p>
    {% elseif currentDate < session.dateSessionFinFormat  %}
        <p class="zero center">Cette session est <b>ouverte.</b></p>
    {% else %}
        <p class="zero center">Cette session est <b>terminée.</b></p>
    {% endif %}

    <div class="topPage2">
        <div class="colTop">
        <p class="center">Modules inclus dans cette session de formation</p>

        <ul class="modules">
            {% for programme in session.programmes %}
                <li> 
                    {{ programme.moduleSession }} {{programme.nbjours}} jours. 
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{path ('removeProgramme', {'id' : session.id , 'programme' : programme.id }) }}" class="looksLikeAButton">Enlever</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
        </div>
        {% if is_granted("ROLE_ADMIN") %}
            <div class="colTop">
            <p class="zero center">Ajouter un module dans la session ? </p>
            <ul>
                {% for module in modulesnonconcernes %}
                    <li>
                        <form method="post" action="{{ path('addModule', {'id' : module.id , 'session' : session.id , 'moduleSession' : module.id}) }}"
                            <label for="number{{ module.id }}">{{module}} </label>
                            <input type="number" id="number{{ module.id }}" name="number" required>
                            <input type="submit" value="Ajouter" class="looksLikeAButtonGreen"> 
                        </form>
                    </li>
                {% endfor %} 
            </ul>
            </div>
        {% endif %}
    </div>

        <p class="zero center">Voici les stagiaires qui se sont inscrits à la session</p>

            <table>
                <thead>
                    <tr>
                        <th class="boldItalicBasic">Stagiaire</td>
                        <th class="boldItalicBasic">Etat</td>
                        {% if is_granted("ROLE_ADMIN") %}
                            <th class="boldItalicBasic">Actions</td>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% if allStagiaires is empty %}
                        <p>Il n'y a aucun stagiaire</p>
                    {% endif %}
                    {% for stagiaire in allStagiaires %}
                        {% if stagiaire is empty %}
                            <p>Il n'y a aucun stagiaire</p>
                        {% endif %}
                        <tr>
                            <td><span class="boldNoColorChange">{{stagiaire}}</span></td>
                            {% if session in stagiaire.sessions %}
                                <td><b>Inscrit</b></td>
                            {% else %}
                                <td><b>Non inscrit</b></td>
                            {% endif %}
                            {% if is_granted("ROLE_ADMIN") %}
                                {% if session in stagiaire.sessions %}
                                    <td><a class="looksLikeAButtonScarlet" href=" {{ path('removeStagiaire', {'id' : stagiaire.id , 'session' : session.id }) }}">Désinscrire</a></td>
                                {% else %}
                                    <td><a class="looksLikeAButtonGreen" href=" {{ path('addStagiaire', {'id' : stagiaire.id , 'session' : session.id }) }}">Inscrire</a></td>
                                {% endif %}
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        {# <ul>
            {% for stagiaire in session.stagiaires %}
                <li> <a href=" {{ path("detailStagiaire" , {'id' : stagiaire.id }) }}">{{stagiaire}}</a></li>
                {% if is_granted('ROLE_ADMIN') %}
                    <a href=" {{path ('removeStagiaire', {'id' : stagiaire.id , 'session' : session.id }) }}">- </a>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        {% if session.stagiaires is empty %}
            <p class="zero">Aucun stagiaire n'a été trouvé.</p>
        {% else %}
        <p class="zero">Voici les stagiaires qui étaient inscrits à la session : </p>
        <ul>
            {% for stagiaire in session.stagiaires %}
                <li>
                    <a href=" {{ path("detailStagiaire" , {'id' : stagiaire.id }) }}">{{stagiaire}}</a>
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href=" {{ path('removeStagiaire', {'id' : stagiaire.id , 'session' : session.id }) }}">-</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endif %}
    {% if is_granted('ROLE_ADMIN') %}     #}

        {# <p class="zero">Ajouter un stagiaire à la session ? </p>  #}
        {# <ul>
            {% for stagiaire in stagiairesNonInscrits %}
                <li>
                    <a href=" {{path ('detailStagiaire', {'id' : stagiaire.id}) }}">{{ stagiaire }}</a> 
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href=" {{path ('addStagiaire', {'id' : stagiaire.id , 'session' : session.id }) }}">+</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul> #}
        {# <p class="zero">Ajouter un module dans la session ? </p>
        <ul>
            {% for module in modulesnonconcernes %}
                <li>
                    <form method="post" action="{{ path('addModule', {'id' : module.id , 'session' : session.id , 'moduleSession' : module.id}) }}"
                    <label for="programme"> {{module}} </label>
                    <input type="number" name="number" required>
                    <input type="submit">
                    </form>
                </li>
            {% endfor %}  #}
    {# </ul> #}

</div>
<script src="{{ asset('js/toggleEncardBis.js') }}"></script>        
{% endblock %}

templates/session/index.html.twig
{% extends 'leaflet.html.twig' %}

{% block meta %}
<meta name="description" content="Vue globale des sessions">
{% endblock %}
{% block title %}Hello SessionController!{% endblock %}

{% block body %}
    <h1>Liste des sessions</h1>
    {% if is_granted('ROLE_ADMIN') %}
        <p class="topPage">
            <a class="looksLikeAButtonGreen" href=" {{ path('newSession')}} ">Ajouter une session</a>
        </p>
    {% endif %}
    <div class="board">
        {% for session in sessions %}
            <div class="colTop">
                <a href=" {{ path("detailSession" , {'id' : session.id}) }}"><b>{{ session.titre }}</b></a>
                <p>Places Max : {{session.places}} </p>
                {% if currentDate < session.dateSessionFinFormat %}
                    <p>Place(s) restantes : {{ session.placesRestantes }}</p>
                {% else %}
                    <p>La session est fermée</p>
                {% endif %}
                {% if is_granted('ROLE_ADMIN') %}
                    <p><a href=" {{ path("deleteSession" , {'id' : session.id}) }}" class="looksLikeAButtonScarlet">Supprimer la session</a></p>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    <div class="map-wrapper">
        <div id="map" class="map-middle" data-marqueurs="{{ marqueurs }}">

        </div>
    </div>
        
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
crossorigin=""></script>
<script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol/dist/L.Control.Locate.min.js" charset="utf-8"></script>
<script src="{{ asset('js/mapBis.js') }}"></script>   
<script src="{{ asset('js/toggle.js') }}"></script>    
{% endblock %}

templates/session/new.html.twig
{% extends 'leaflet.html.twig' %}

{% block meta %}
<meta name="description" content="Ajouter une session">
{% endblock %}

{% block title %} Ajouter session {% endblock %}

{% block body %}
<h1>Ouvrir une session</h1>
<div class="formGlobal">
    {{ form_start(formNewSession) }}
        <div class="formInside">
            <div class="formRow">
                {{ form_label(formNewSession.titre)}}
                {{ form_widget(formNewSession.titre)}}
                {{ form_help(formNewSession.titre)}}
                {{ form_errors(formNewSession.titre)}}
            </div>
            <div class="formRow">
                {{ form_label(formNewSession.dateSessionDebut)}}
                {{ form_widget(formNewSession.dateSessionDebut)}}
                {{ form_help(formNewSession.dateSessionDebut)}}
                {{ form_errors(formNewSession.dateSessionDebut)}}
            </div>
            <div class="formRow">
                {{ form_label(formNewSession.dateSessionFin)}}
                {{ form_widget(formNewSession.dateSessionFin)}}
                {{ form_help(formNewSession.dateSessionFin)}}
                {{ form_errors(formNewSession.dateSessionFin)}}
            </div>
            <div class="formRow">
                {{ form_label(formNewSession.places)}}
                {{ form_widget(formNewSession.places)}}
                {{ form_help(formNewSession.places)}}
                {{ form_errors(formNewSession.places)}}
            </div>
            <div class="formRow">
                {{ form_label(formNewSession.formation)}}
                {{ form_widget(formNewSession.formation)}}
                {{ form_help(formNewSession.formation)}}
                {{ form_errors(formNewSession.formation)}}
            </div>
            <div class="formRow">
                {{ form_label(formNewSession.formateur)}}
                {{ form_widget(formNewSession.formateur)}}
                {{ form_help(formNewSession.formateur)}}
                {{ form_errors(formNewSession.formateur)}}
            </div>
            <div class="formRow">
                {{ form_label(formNewSession.coordonnees)}}
                {{ form_widget(formNewSession.coordonnees)}}
                {{ form_help(formNewSession.coordonnees)}}
                {{ form_errors(formNewSession.coordonnees)}}
            </div>
            {{form_row(formNewSession.valider)}}
        </div>
    {{ form_end(formNewSession) }}

    <div id="map">

    </div>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin=""></script>
    <script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol/dist/L.Control.Locate.min.js" charset="utf-8"></script>
    <script src="{{ asset('js/map.js') }}"></script>    
    <script src="{{ asset('js/toggleForm.js') }}"></script>    
</div>    
{% endblock %}